services:
  robomerge:
    image: robomerge:latest
    restart: unless-stopped
    networks:
      - localnet
    env_file:
      - .env
    ports:
      - "8877:8877"
      - "1666:1666"
    environment:
      NODE_ENV: ${NODE_ENV}
      P4PORT: ${P4PORT}
      P4USER: ${P4USER}
      P4PASSWD: ${P4PASSWD}
      BOTS: ${BOTS}
      ROBO_LOG_LEVEL: ${ROBO_LOG_LEVEL}
      ROBO_EXTERNAL_URL: "http://localhost:8877"
    volumes:
      - ~/.p4trust:/root/.p4trust:ro
    entrypoint: sh -c "p4 -p $P4PORT trust -y && node --require source-map-support/register dist/robo/watchdog.js"

networks:
  localnet:
    driver: bridge
